manifest:
  version: 0.7
 
  defaults:
    remote: nrfconnect

  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.9.1
      import:
        path-prefix: deps
        name-allowlist:
          - zephyr
          - cmsis
          - hal_nordic
          - mbedtls
          - net-tools
          - nrf_hw_models
          - segger
          - tinycrypt
          - tf-m-tests
          - nrfxlib
          - mcuboot
          - mcumgr
          - tinycbor
          - mbedtls-nrf
          - memfault-firmware-sdk
          - openthread

    # Golioth repository.
    - name: golioth
      path: deps/modules/lib/golioth
      revision: v0.2.0
      url: https://github.com/golioth/zephyr-sdk.git

    # QCBOR
    - name: qcbor
      path: deps/modules/lib/qcbor
      revision: 17b5607b8c49b835d22dec3effa97b25c89267b3
      url: https://github.com/golioth/QCBOR.git

  self:
    path: app
    west-commands: scripts/west-commands.yml
